# Generated by Django 6.0.4 on 2026-04-14 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('head', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('leader', models.CharField(max_length=100)),
                ('jira_project', models.CharField(blank=True, max_length=100, null=True)),
                ('github_repo', models.CharField(blank=True, max_length=200, null=True)),
                ('jira_board', models.CharField(blank=True, max_length=200, null=True)),
                ('development_focus', models.TextField(blank=True, null=True)),
                ('key_skills', models.TextField(blank=True, null=True)),
                ('downstream_dependencies', models.CharField(blank=True, max_length=200, null=True)),
                ('dependency_type', models.CharField(blank=True, max_length=100, null=True)),
                ('slack_channels', models.CharField(blank=True, max_length=200, null=True)),
                ('standup_time', models.CharField(blank=True, max_length=100, null=True)),
                ('agile_practices', models.CharField(blank=True, max_length=200, null=True)),
                ('team_wiki', models.CharField(blank=True, max_length=200, null=True)),
                ('concurrent_projects', models.CharField(blank=True, max_length=50, null=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='core.department')),
            ],
        ),
    ]
